# See https://alacritty.org/config-alacritty.html
# to read and understand configuration file

[general]
import = ["~/.config/alacritty/themes/themes/snazzy.toml"]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[env]
term = "xterm-256color"
COLORTERM = "truecolor"

[window]
opacity = 1
blur = false
padding = { x = 8, y = 8 }
dynamic_padding = false
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "OnlyLeft"
level = "Normal"

[scrolling]
history = 10000
multiplier = 4

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
size = 14
builtin_box_drawing = true

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true

[bell]
animation = "Ease"
duration = 0

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = false
